name: CD - Deploy (Local Windows Runner)

on:
  workflow_dispatch:  # thêm dòng này để test thủ công
  workflow_run:
    workflows: ["CI + CD (Delivery) - Spring Boot"]
    types: [completed]
    branches: [main]

jobs: 
  deploy:
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Pull & Run Docker Image
        run: |
          docker pull haolongd/springboot-app:latest
          if (docker ps -q -f name=^app$) { docker stop app }
          if (docker ps -aq -f name=^app$) { docker rm app }
          docker run -d --restart unless-stopped `
            --env-file C:\opt\app\.env `
            -p 8080:8080 `
            --name app haolongd/springboot-app:latest
          docker image prune -f
