name: CD - Deploy (Local Windows Runner)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy_trigger]

jobs: 
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull & Run Docker Image
        run: |
          docker pull haolongd/springboot-app:latest
          if (docker ps -q -f name=^app$) { docker stop app }
          if (docker ps -aq -f name=^app$) { docker rm app }
          docker run -d --restart unless-stopped `
            --env-file C:\opt\app\.env `
            -p 8080:8080 `
            --name app haolongd/springboot-app:latest
          docker image prune -f
