name: CD - Deploy (Local Windows Runner)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy_trigger]

jobs: 
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with docker-compose
        run: |
          cd Backend
          docker compose pull app
          docker compose up -d
          docker image prune -f
