name: CD - Deploy (Local Windows Runner)

on:
  workflow_run:
    workflows: ["CI + CD (Delivery) - Spring Boot"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull & Run Docker Image
        run: |
          docker pull haolongd/springboot-app:latest
          docker stop app || exit 0
          docker rm app || exit 0
          docker run -d --restart unless-stopped `
            --env-file C:\opt\app\.env `
            -p 8080:8080 `
            --name app haolongd/springboot-app:latest
          docker image prune -f
